imports:
  - { resource: ../common.yml }

services:
  ps_checkout.logger.file.finder:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileFinder'
    arguments:
      - '@ps_checkout.logger.directory'
      - '@ps_checkout.module'

  ps_checkout.logger.file.reader:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileReader'

  ps_checkout.step.live:
    class: 'PrestaShop\Module\PrestashopCheckout\Step\LiveStep'
