services:
  _defaults:
    public: true

  ps_checkout.module:
    class: 'Ps_checkout'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ps_checkout'

  ps_checkout.shop.provider:
    class: 'PrestaShop\Module\PrestashopCheckout\Shop\ShopProvider'

  ps_checkout.configuration.options.resolver:
    class: 'PrestaShop\Module\PrestashopCheckout\Configuration\PrestaShopConfigurationOptionsResolver'
    arguments:
      - '@=service("ps_checkout.shop.provider").getIdentifier()'

  ps_checkout.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\Configuration\PrestaShopConfiguration'
    arguments:
      - '@ps_checkout.configuration.options.resolver'

  ps_checkout.cache.directory:
    class: 'PrestaShop\Module\PrestashopCheckout\Cache\CacheDirectory'
    arguments:
      - !php/const _PS_VERSION_
      - !php/const _PS_ROOT_DIR_
      - !php/const _PS_MODE_DEV_

  ps_checkout.logger.directory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory'
    arguments:
      - !php/const _PS_VERSION_
      - !php/const _PS_ROOT_DIR_

  ps_checkout.logger.filename:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFilename'
    arguments:
      - '@=service("ps_checkout.module").name'
      - '@=service("ps_checkout.shop.provider").getIdentifier()'

  ps_checkout.logger.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerConfiguration'
    arguments:
      - '@ps_checkout.configuration'

  ps_checkout.env.sentry:
    class: 'PrestaShop\Module\PrestashopCheckout\Environment\SentryEnv'

  ps_checkout.logger.sentry.handler:
    class: 'PrestaShop\Module\PrestashopCheckout\Sentry\SentryHandler'
    arguments:
      - '@ps_checkout.env.sentry'

  ps_checkout.logger.handler.factory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerHandlerFactory'
    arguments:
      - '@=service("ps_checkout.logger.directory").getPath()'
      - '@=service("ps_checkout.logger.filename").get()'
      - '@=service("ps_checkout.logger.configuration").getMaxFiles()'
      - '@=service("ps_checkout.logger.configuration").getLevel()'

  ps_checkout.logger.handler:
    class: 'Monolog\Handler\HandlerInterface'
    factory: ['@ps_checkout.logger.handler.factory', 'build']

  ps_checkout.logger.factory:
    class: 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFactory'
    arguments:
      - '@=service("ps_checkout.module").name'
      - '@ps_checkout.logger.handler'
      - '@ps_checkout.logger.sentry.handler'

  ps_checkout.logger:
    class: 'Psr\Log\LoggerInterface'
    factory: ['@ps_checkout.logger.factory', 'build']
    arguments:
      - '@ps_checkout.logger.directory'

  ps_checkout.logger.sentry.processor:
    class: 'PrestaShop\Module\PrestashopCheckout\Sentry\SentryProcessor'
    
  ps_checkout.paypal.configuration:
    class: 'PrestaShop\Module\PrestashopCheckout\PayPal\PayPalConfiguration'
    arguments:
      - '@ps_checkout.configuration'
