name: Module checkout CD Production Beta

on:
  push:
    branches:
      - feature/continuous-delivery
#on:
#  push:
#    tags:
#      - '*'

env:
  MODULE_NAME: ps_checkout
  GCLOUD_TOKEN_PATH: ./token.json

jobs:
  checkout_cd:
    name: Module Accounts continuous deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Gcloud auth and write env file
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > $GCLOUD_TOKEN_PATH
          gcloud auth activate-service-account --key-file=$GCLOUD_TOKEN_PATH
          gcloud container clusters get-credentials $GCLOUD_CLUSTER \
          --zone europe-west1-c --project $GCLOUD_PROJECT
          rm $GCLOUD_TOKEN_PATH
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIAL_PRODUCTION }}
          GCLOUD_TOKEN_PATH: ${{ env.GCLOUD_TOKEN_PATH }}
          GCLOUD_CLUSTER: ${{ secrets.GCLOUD_CLUSTER }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT_PRODUCTION }}

      - name: Build module
        run: |
          yarn
          yarn build
          composer install

      - name: Delete old module
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: sudo su -c 'docker exec $(docker ps -aqf "name=${{ secrets.CONTAINER_NAME }}") rm -rf modules/${{ env.MODULE_NAME }}'

      - name: Copy module
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ env.MODULE_NAME }}

      - name: Move module
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'mv ${{ env.MODULE_NAME }} ${{ secrets.MODULE_PATH }}'
            sudo su -c 'chown -R www-data:www-data ${{ secrets.MODULE_PATH }}/${{ env.MODULE_NAME }}'

      - name: Install module
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -aqf "name=${{ secrets.CONTAINER_NAME }}") bin/console prestashop:module install ${{ env.MODULE_NAME }}'

      - name: Clear cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -aqf "name=${{ secrets.CONTAINER_NAME }}") bin/console cache:cl'
            sudo su -c 'docker exec $(docker ps -aqf "name=${{ secrets.CONTAINER_NAME }}") chmod -R 777 var/cache var/logs'
